name: Run Web Test Runner Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: which google-chrome || which chromium || which chromium-browser
    #   - run: npm ci
    #   - run: sudo apt-get update && sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium
    #   - run: npm test
